server:
  port: 9999


spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  neo4j:
    uri: bolt://localhost:7687
#    authentication:
#      username: neo4j
#      password: secret
    migrations:
      enabled: true